### ISSUE TITLE
Error I get with PHP Samples

### ISSUE THREAD

**Issue by DevelopersWork** [youtube/api-samples#118]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\Projects\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\xampp\htdocs\Projects\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\Projects\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\Projects\php\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\Project in C:\xampp\htdocs\Projects\php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by themood54** [comment]
i have all working samples that work in php for facebook ill upload them in a minute

**Comment by dwilbanks** [comment]
This is a very old post, but, since it's still an issue for at least one person (me), here's the answer.

This message is caused by upgraded SSL certificates on the google server that the server does not know about.

The code is in fact working, but, it does not have significant error handling to deal with this very, very predictable problem.

there are lots of documented fixes like this one:
https://medium.com/@narendravaghela/how-to-fix-curl-error-60-ssl-certificate-problem-80e7dafafa57

Make sure you update the correct php.ini if your server has more than one.
